# -*- coding: utf-8 -*-
"""MergePDF_PyPDF4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxbIFWF2hJUuNWRboI5l_gPNhb4SEhjR
"""

!pip install PyPDF4
!pip3 install PyPDF4

#https://pypdf2.readthedocs.io/en/latest/user/cropping-and-transforming.html
#https://github.com/claird/PyPDF4
#https://pythonguides.com/pdffilewriter-python-examples/

import PyPDF4

from PyPDF4 import PdfFileMerger
from PyPDF4 import PdfFileWriter, PdfFileReader

#Merge 2 PDFs
merger=PdfFileMerger()
file1="/content/chapter1.pdf"
file2="/content/chapter2.pdf"

for page in [file1,file2]:
  merger.append(page)

merger.write("merged.pdf")
merger.close()

#Merge certain pages of a file
merger=PdfFileMerger()
file1="/content/chapter1.pdf"
file2="/content/chapter2.pdf"

merger.append(file1,pages=(1,3))
merger.append(file2,pages=(1,2))

merger.write("merged_page.pdf")
merger.close()

#Merge selected number of pdfs by entering the path for each, and make into 1 
merger=PdfFileMerger()
number=int(input('Please enter the number of pdfs you want to merge: '))
document_list=[]

for each in range(number):
  document_list.append(input("Please enter the path for the document: "))

for file in document_list:
  merger.append(file)

merger.write('Multiple_pdf.pdf')
merger.close()

#Below 2 methods are dealing with selecting certain pages from the pdf into new one
read_file=PdfFileReader("/content/Top_Korean_100_Words_PDF-1.pdf")
new_file=PdfFileWriter()
new_file.addPage(read_file.getPage(1))
new_file.addPage(read_file.getPage(2))
new_file.addPage(read_file.getPage(4))

with open("deleted_page1.pdf","wb") as fp:
  new_file.write(fp)

delete=[1,3,5]

#file=open("/content/Justlearn-Advanced-Spanish-Vocabuary-List.pdf","rb")
#read_file=PdfFileReader(file)
read_file=PdfFileReader("/content/Justlearn-Advanced-Spanish-Vocabuary-List.pdf")
edit_file=PdfFileWriter()

for i in range(len(read_file.pages)):
  if i not in delete:
    edit_file.addPage(read_file.getPage(i))

with open("cropped_pdf2.pdf","wb") as fp:
  edit_file.write(fp)